---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: postgres
  password: pgsqlpassword
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-tls
  namespace: keycloak
type: Opaque
stringData:
  tls.crt: |-
    "-----BEGIN CERTIFICATE-----
    MIIDczCCAlugAwIBAgIUTdC5NWFgm7aIzq8cTSDDakPx2aswDQYJKoZIhvcNAQEL
    BQAwSTEhMB8GA1UEAwwYZGV2ZWxvcG1lbnQua2V5Y2xvYWsub3JnMRcwFQYDVQQK
    DA5UZXN0IEtleWNsb2FrLjELMAkGA1UEBhMCVVMwHhcNMjQwNjEyMDQzODM0WhcN
    MjUwNjEyMDQzODM0WjBJMSEwHwYDVQQDDBhkZXZlbG9wbWVudC5rZXljbG9hay5v
    cmcxFzAVBgNVBAoMDlRlc3QgS2V5Y2xvYWsuMQswCQYDVQQGEwJVUzCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAJLx1IF26EQwdweCI74p37aJzADLIaZU
    +QvG4Oi9606yllz3Dz5PWTl7XWMuVUjIY7IWU3kmFXaPWy7sB93n/4fgd3EsY7KV
    ZzgNcy41fpp8BBIBqwEoO5EN7GIIf7+0CyDMGRByNvUKZmPU7O8Q8FljSRaBfidi
    3Xni+JNA+ngnpZYlbRSCb8z9mXZHG/vKlezyDUjFk7Tm6DpUahRFvWY3gEGFJnth
    wUzqankx1w9J6MYHirnbLoBlw6AICsZfiH+xJDZLaggAgnn+Aru3h0MtBVMGWTmT
    2rH7txYT7dw2oXCyd6wiuI+FOIXk0SmnOAqwZAZ2Nxri6jZLOlvun+ECAwEAAaNT
    MFEwHQYDVR0OBBYEFE92nwlzTdemEssNlfhLIn3Ek25RMB8GA1UdIwQYMBaAFE92
    nwlzTdemEssNlfhLIn3Ek25RMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggEBABaX2u3AoEYWSSgSY5DgC8GmYVPsa2hYo8ABQM5bBbOZ9u++qs21Djcw
    RQbJqGZMk927KIo24Ts2ernLCEg8BRYpwyYTYYL7p2B7FnzguRXjjh40u/D6H2y9
    /IsBoeztQ0W9I7syFhRsTzTlb07ER9N99UK3CLNItALGsNbYcpx99r/hTkicUdNN
    +FoET+lE9eaoDfIEHSdEAjdcr2r5Jb7MwJ572UYQQFzjnnaZMV1uHUn0OoQMt2W7
    JzgaUF8Na80x7MfBFAGperonTzN2w2XFor6Z7ycEziUIIU4CLkiWYWTWDlTlkQhr
    Pofp4cPebJM76aJvhQcNhfBGkKqA1rg=
    -----END CERTIFICATE-----"
  tls.key: |-
    "-----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCS8dSBduhEMHcH
    giO+Kd+2icwAyyGmVPkLxuDovetOspZc9w8+T1k5e11jLlVIyGOyFlN5JhV2j1su
    7Afd5/+H4HdxLGOylWc4DXMuNX6afAQSAasBKDuRDexiCH+/tAsgzBkQcjb1CmZj
    1OzvEPBZY0kWgX4nYt154viTQPp4J6WWJW0Ugm/M/Zl2Rxv7ypXs8g1IxZO05ug6
    VGoURb1mN4BBhSZ7YcFM6mp5MdcPSejGB4q52y6AZcOgCArGX4h/sSQ2S2oIAIJ5
    /gK7t4dDLQVTBlk5k9qx+7cWE+3cNqFwsnesIriPhTiF5NEppzgKsGQGdjca4uo2
    Szpb7p/hAgMBAAECggEADcpZRa8pnCCqQw+hGBso7iIffaGSrmACIWtQNzd/qlqT
    RvU+vnvG5WChAopaIaMAzDlRKyj6Ua6hgZVQJbC8p/1WaE4gqyVfUwDcIuWNVKU3
    4pK6gDjM4k+atBaVGqIkezb8UTFO3A9WTZ8xfzwpOlJZjR2o/7xFCcfVyUgLWZRG
    feeB6+ZeaJhz+SzRXFmu+8lo3snzVsFDNkNSPg6Vy5L0g6VH0OiwQUE1krr5MFqe
    scWxgwJMEbeHHJnEsPFzDk/0u3HYgOJHBCznks4FuQSr2himQvh7MRRokm+yqMWA
    BWdZuEwZcaTlxuNWq6WC13Hhowr//p5XrvV24vrAAwKBgQDM4Sb7MJ4nmlUEDTDb
    GkXcp3fYaLH7zNfEDS/YFO+v7BMXE//T7eotWlxsaKA8rGJStksbYY86OOUxJuFN
    Xmcy47uDF36TSoleKD7N+geJnfn7V12g/1mOqpqKJhEALtG2pkNX+PgXIbNyRkvT
    UHxQTNj/vAJIKEH7btUOn9Ij0wKBgQC3nAqLI1/+EchMFj7q0bMzyfIiuDWiqEn/
    QYlb+e6wYahfKdMt4AvUtvPZpb4J4Tdql1OTYbYcB0DwM7rSMBX4QnMUAL7QbLoD
    Rd3vHPuTjCry5GRW7fcHLrV0fkmENPPWS619fYXA2AwHUEM/HPvvQZv+LD/8namu
    haZq+5SA+wKBgQC2djZ/MtdHMd1RFGZUW1uoncTQCL2qIM5wHcZkTJECPd7qiLco
    CRSre3QgYDWEk4mlXBAbvJEQKyeC1LuGafLCkaqnnz7s8k7Qekskqe4Yk4bUXwRV
    o9QgiLPFIQ22+ftvDTegm2xnPW5Q8WYKNf3gjfAcIVZu6NuKjzRUJ+XAXQKBgEV6
    5wKAAHNEh2dDg8uYTxfp85bv3lwPEvFk+3WyvoBAdFaOnTte7RsxoFVcQu26LB5J
    5XaAI0m39PrwmGGxkJ7BhoqrPYnhmwJiDfnOHeVXxWjkxJOguToeksvifi9pWlxd
    hulV9qdjGioqVUgsz6laSo2EcTJG907zhGY3jZrBAoGBAMuhHbFno44ZzA5+AwQ1
    sMJ+tFMyyuuOc/ptE0v+EhKsvZ5S9ZyIgCvDTrTSQzjZRx/ma+zPJ9GBT0ZwgsB6
    u0Bp7a6z+JVAmnBALHQAip+6IEO4ObYInvu6r9RbjibboW4yeBzbGK3A/hMm9hE4
    qYlNc2B07ncxqS5DUZAU/IBf
    -----END PRIVATE KEY-----"