---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  username: postgres
  password: pgsqlpassword
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "5"
  name: keycloak-tls
  namespace: keycloak
type: Opaque
stringData:
  tls.crt: |-
    "-----BEGIN CERTIFICATE-----
    MIIDczCCAlugAwIBAgIUYr6L8uZonKgbB3xSxGzix6xnHv4wDQYJKoZIhvcNAQEL
    BQAwSTEhMB8GA1UEAwwYZGV2ZWxvcG1lbnQua2V5Y2xvYWsub3JnMRcwFQYDVQQK
    DA5UZXN0IEtleWNsb2FrLjELMAkGA1UEBhMCVVMwHhcNMjQwNjEyMDM1NzA0WhcN
    MjUwNjEyMDM1NzA0WjBJMSEwHwYDVQQDDBhkZXZlbG9wbWVudC5rZXljbG9hay5v
    cmcxFzAVBgNVBAoMDlRlc3QgS2V5Y2xvYWsuMQswCQYDVQQGEwJVUzCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALo6152/ZlXZDYMFxx95+j9rkQRUqTFK
    OCoz+kUM7YLk19YGXc74M+XN5ZwWOz/XtiD4dE4ywG7DdiMekZIzXjdHPmFjT/dD
    1uyv2z85lPc1MujJMp5M+SRV/RLVXk+OfRlNpB1gUXBTTTms5A6N8ziiGO/B6/GQ
    nwO92QHUGuVjpoRABeGjKyR5K9iTKOAwIvNdhMhTa1Yme7RpxtmvNzIhL+7XGIuV
    bIz/nUgNzvMmNQQwWvpjODil2QwpgwMe9hdx4T/XvsClULsp/Q6/AiL9uLG+J0Z3
    wEp0zQ6nk0I8eyOA2gKBD6tjMIXH43A9AYK0HIQjluuiVLckMnt6cAsCAwEAAaNT
    MFEwHQYDVR0OBBYEFAHPdy/idXvKvkJUeXSZrMfTgqGEMB8GA1UdIwQYMBaAFAHP
    dy/idXvKvkJUeXSZrMfTgqGEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggEBAKx/hyBkKYjBhvxCxpz9DgLymvH6wgAB6Tc0FRWzSISX2XI0/4voncFG
    dArIDsKDTozdYgF1TVgUTUpAbrW4JeLEFncoOERIva7TYb7YhFX8+QntLHDExMYA
    OmhDE4dlg8e4uLYdDz5anDchHwfs1jBN3pfJ5jRuWfFIGO7cPf3sAUz3HR/erwvG
    B4/QjYyvJvAZO5IELCwVOpq+aNWg1Ah2GZgMTPCzX2WL7cPrHNSpL9sPpeOvRuBX
    XtX2a2rp09noPP+SYpE0fLunwQYv6XSKQ1aXlGFXtOb6lrOKhJtU0JPVA5tJ5ImI
    GVyPPoMqvN8dU14W/a+ZgjsyeTrBmz8=
    -----END CERTIFICATE-----"
  tls.key: |-
    "-----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6Otedv2ZV2Q2D
    Bccfefo/a5EEVKkxSjgqM/pFDO2C5NfWBl3O+DPlzeWcFjs/17Yg+HROMsBuw3Yj
    HpGSM143Rz5hY0/3Q9bsr9s/OZT3NTLoyTKeTPkkVf0S1V5Pjn0ZTaQdYFFwU005
    rOQOjfM4ohjvwevxkJ8DvdkB1BrlY6aEQAXhoyskeSvYkyjgMCLzXYTIU2tWJnu0
    acbZrzcyIS/u1xiLlWyM/51IDc7zJjUEMFr6Yzg4pdkMKYMDHvYXceE/177ApVC7
    Kf0OvwIi/bixvidGd8BKdM0Op5NCPHsjgNoCgQ+rYzCFx+NwPQGCtByEI5brolS3
    JDJ7enALAgMBAAECggEADEKUcE+p8ovkDlSii8lxdpxjwye5rcOHmAus9b/IoR3k
    sbPgmCAR9paL/68c/nJ6jIgezAkeTwxyKhS4m6njEXuQuUOa/5nJO/LF2c82JeIs
    NFQOj4pcuo4op4VBfLZSOQi5/a8aHW12f44Iw4aH1RoizyHyoQgW1923PB4VGTXN
    51TWW4SWKwWbYLQqH+RJdSItH5fruARLw3Mf8ftaYwscbXpMGT6xokueCmG/TYMZ
    81Lb4jvbPknJYPXd4P2zAuHkdkD0V9+8WmR5wHg0qYe/2nJENMzbJC0GZQNWp9bD
    7nvuPaeracQIqC+opXAwUh0aH8g7miwTqFgMvdZz6QKBgQDtFmjijicZYZwYBuhn
    G5RSJs4JJralGbMIW8AqQtg/Sl5tG/7RvIbPjv6X/er99CQ8qVWyXBEyT63Uhqrs
    vvAWJdeqGqq3T6aGChdP5s8MXaJKx28oDNtKpcKeKyA8Gb/1woyXI2FAxZdwMCFv
    cQkUuNurm3A1TdZmWkFJ3DUT8wKBgQDJFdy74mztj340/5bzAzZNfvFPjygahmGa
    lOx1ZGrHdu+PfmXnfCYljUhZz+OkvyO0Rc00/8N4+zZl9tbMNcou+Q38oecRTRfR
    TMcTRkKL2CRQcaTnmxg0q3rhAnU7vCVP/gWDqPyPLQfNfmyU+zUgPlMDPEhCWkNS
    pLLm2UnxiQKBgQDC97jNBmV04+Y/g/6+O9nfLPYmZGWyo82sw/blSg8XDQtV4r3M
    sKKUMV2AlFkY+hqKoB5PDJM/snKa4RvSkLpTHE+cHU3ibWfdtpKxLHd8DcwWfqcU
    Ym47ltDSzVg21F4dth1zdK7XWyZMJeh5ApWbKuHK34qI6zey9+nU2Xf0rQKBgQCA
    +Ma0swtOawR1laEJiHvhxJOdhaIhMSOU9AOdX6Sk/oG0NUvC5vvIhg9rm0zUs8uA
    qmxtm8WR6P4A9Arcu3tMGW2BJY6AqEOoeGgO0reH3j+cYOd1rSIfVgTgIKV0hL4h
    yjlbMp2abzVb9cRK4bw3TAIORzHJbP9VGFGugptMkQKBgCa/MbFYlNsUDV2B+rDE
    hut5Pd7Ho4/52BXy4o4eAPwNtee/KL0R3zGCTBVgrC33Ycfj20WXhyPE6e8AGQwP
    fRiybMCOCEpSTUNheDSV21PHQUWQn23BSguXULtucOIqopnfypm4wPXJX5/vibt6
    hs+1srrHgjPy3i/f94pMo9Mk
    -----END PRIVATE KEY-----"